### ISSUE TITLE
Tio many arguments for usb!

### ISSUE THREAD

**Issue by zparta** [knxd/knxd#285]
When i try to start knxd with usb:1:4:1:0:0 which is the correct deviceid i get the error "Too many arguments for usb!" I have tried to modify knxd_args.cpp and commented out the if atriums that section and that makes knxd start but i have major lag to the bus.
knxtool commands lags behandlas lets say i send an on command IT does not activate butik i send aborter command IT there are sometimes several commands behind.
And knxtool sometimes does not send the command to the bus and gives an error with connection timed out and this is from localhost
IF you want more information just tell me what you want and il get IT to you.

Hardware merten 135E 0025, raspberry pi this is with latest stable from github

**Comment by zparta** [comment]
Newly compiled from sources i still get this error.
Why do i get this error?
Here is the device:
```
[    3.226618] usb 1-1.3: new full-speed USB device number 4 using dwc_otg
[    3.407114] usb 1-1.3: New USB device found, idVendor=135e, idProduct=0025
[    3.417698] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.432042] usb 1-1.3: Product: KNX-USB Data Interface
[    3.440856] usb 1-1.3: Manufacturer: Hager Electro
```
Here is my command line arguments.
```
pi@raspberrypi:~/knx/knxd/src/server$ ./knxd_args --eibaddr=0.0.1 --client-addrs=0.0.2:8 -d -D -T -R -S -i --listen-local=/tmp/knx -b usb:1:4:1:0:0
Too many arguments for usb!
pi@raspberrypi:~/knx/knxd/src/server$

```

**Comment by smurfix** [comment]
Thanks, will investigate. In the meantime simply drop the extra options. Usually knxd finds the device by itself, "-b usb:" without any numbers should be sufficient.

**Comment by zparta** [comment]
Thanks for it to work without '1:4:1:0:0' but got another error instead.

I can only send one or two commands then it drops and i need to restart knxd, this works in 0.12 version but not in 0.14 version.

This is what i get in my messages log:
```
Nov 16 20:30:38 raspberrypi kernel: [   63.529750] hid-generic 0003:135E:0025.0003: hiddev0,hidraw0: USB HID v1.01 Device [Hager Electro KNX-USB Data Interface] on usb-3f980000.usb-1.3/input0
Nov 16 20:30:51 raspberrypi kernel: [   76.108579] hid-generic 0003:135E:0025.0004: hiddev0,hidraw0: USB HID v1.01 Device [Hager Electro KNX-USB Data Interface] on usb-3f980000.usb-1.3/input0
Nov 16 20:31:03 raspberrypi kernel: [   88.221606] hid-generic 0003:135E:0025.0005: hiddev0,hidraw0: USB HID v1.01 Device [Hager Electro KNX-USB Data Interface] on usb-3f980000.usb-1.3/input0
Nov 16 20:31:54 raspberrypi kernel: [  139.648061] hid-generic 0003:135E:0025.0006: hiddev0,hidraw0: USB HID v1.01 Device [Hager Electro KNX-USB Data Interface] on usb-3f980000.usb-1.3/input0
Nov 16 20:32:31 raspberrypi kernel: [  176.520594] hid-generic 0003:135E:0025.0007: hiddev0,hidraw0: USB HID v1.01 Device [Hager Electro KNX-USB Data Interface] on usb-3f980000.usb-1.3/input0
Nov 16 20:34:59 raspberrypi kernel: [  323.862830] hid-generic 0003:135E:0025.0008: hiddev0,hidraw0: USB HID v1.01 Device [Hager Electro KNX-USB Data Interface] on usb-3f980000.usb-1.3/input0
Nov 16 20:35:48 raspberrypi kernel: [  373.024609] hid-generic 0003:135E:0025.0009: hiddev0,hidraw0: USB HID v1.01 Device [Hager Electro KNX-USB Data Interface] on usb-3f980000.usb-1.3/input0

```
itäs like it resets the device maybe?

**Comment by dallmair** [comment]
Thanks for reporting this problem.

```
Too many arguments for usb!
```

I've sent a PR to fix this.

> it's like it resets the device maybe?

Seems so. As USB has seen a lot of fixes since this issue was created, chances are the issue has been fixed in the meantime. Also, it's impossible to diagnose with the information provided so far and a lot of time has passed. Thus, it does not make sense to keep this issue open, hence it will be closed when PR #641 is merged.

If you can still reproduce this with the current version of knxd, please reopen. In this case we'd need low level traces of the current version to pinpoint the problem, and ideally also from version 0.12 for comparison.
